#!/usr/bin/env bash
# init.sh - Initialize hatch.conf for a project

_header "Hatch Init"

# Detect project name
PROJECT_NAME=$(basename "$PWD")
if git remote get-url origin >/dev/null 2>&1; then
  REMOTE_URL=$(git remote get-url origin)
  PROJECT_NAME=$(basename "$REMOTE_URL" .git)
fi

_info "Detected project: $PROJECT_NAME"
echo ""

# Detect package manager
PACKAGE_MANAGER="none"
if [[ -f "bun.lockb" ]]; then
  PACKAGE_MANAGER="bun"
elif [[ -f "pnpm-lock.yaml" ]]; then
  PACKAGE_MANAGER="pnpm"
elif [[ -f "yarn.lock" ]]; then
  PACKAGE_MANAGER="yarn"
elif [[ -f "package-lock.json" ]]; then
  PACKAGE_MANAGER="npm"
fi

_info "Detected package manager: $PACKAGE_MANAGER"

# Detect Docker services
DOCKER_SERVICES=()
DOCKER_EXTRAS=()

if [[ -f "docker-compose.yaml" ]] || [[ -f "docker-compose.yml" ]]; then
  _info "Found docker-compose.yaml"
  
  # Extract service names and ports (basic parsing)
  while IFS= read -r line; do
    if [[ "$line" =~ ^[[:space:]]*([a-z0-9_-]+):[[:space:]]*$ ]]; then
      SERVICE_NAME="${BASH_REMATCH[1]}"
      # Skip 'services:' line itself
      [[ "$SERVICE_NAME" == "services" ]] && continue
      
      # Try to detect port from next few lines
      # This is basic - real parsing would need yaml parser
      _info "  Found service: $SERVICE_NAME"
    fi
  done < <(grep -A 20 "^services:" docker-compose.yaml 2>/dev/null || grep -A 20 "^services:" docker-compose.yml 2>/dev/null)
fi

# Detect migration tool
MIGRATE_TOOL="none"
if [[ -f "prisma/schema.prisma" ]]; then
  MIGRATE_TOOL="prisma"
elif [[ -d "api/migrations" ]] && grep -q "contember" package.json 2>/dev/null; then
  MIGRATE_TOOL="contember"
elif [[ -f "knexfile.js" ]] || [[ -f "knexfile.ts" ]]; then
  MIGRATE_TOOL="knex"
elif [[ -f "drizzle.config.ts" ]] || [[ -f "drizzle.config.js" ]]; then
  MIGRATE_TOOL="drizzle"
fi

# Detect MCP servers
MCP_DETECTED=""
if [[ -f ".mcp.json" ]]; then
  _info "Found .mcp.json (MCP server configuration)"
  MCP_DETECTED="yes"
elif [[ -d "mcp" ]]; then
  _info "Found mcp/ directory (potential MCP server)"
  MCP_DETECTED="yes"
fi

_info "Detected migration tool: $MIGRATE_TOOL"
echo ""

# Ask where to save
echo "Where would you like to save the configuration?"
echo "  1) ./hatch.conf (project root)"
echo "  2) ~/.hatch/projects/${PROJECT_NAME}.conf (user config)"
echo ""
read -p "Choice [1]: " choice
choice="${choice:-1}"

if [[ "$choice" == "2" ]]; then
  CONFIG_FILE="$HOME/.hatch/projects/${PROJECT_NAME}.conf"
  mkdir -p "$(dirname "$CONFIG_FILE")"
else
  CONFIG_FILE="./hatch.conf"
fi

_info "Creating: $CONFIG_FILE"

# Generate config file
cat > "$CONFIG_FILE" << EOFCONFIG
#!/usr/bin/env bash
# Hatch configuration for $PROJECT_NAME
# Generated by hatch init on $(date +%Y-%m-%d)

# Project identity
PROJECT_NAME="$PROJECT_NAME"
PACKAGE_MANAGER="$PACKAGE_MANAGER"

# Docker services (infrastructure)
# Format: "name:container_port" — one per line, space-separated
DOCKER_SERVICES="
  # postgres:5432
  # redis:6379
"

# Docker extras (dev tools with web UI)
DOCKER_EXTRAS="
  # mailhog:8025
  # adminer:8080
"

# Development servers started by 'hatch up'
# Format: "name:directory:command:port_offset"
# Use {PORT} placeholder for dynamic port in command
DEV_SERVERS="
  # web:apps/web:vite --port {PORT} --host 0.0.0.0:10
  # api:apps/api:node --watch src/index.ts:11
"

# Port templates — files needing dynamic port injection
# Format: "file_path:VAR_NAME=value_with_{PORT_servicename}_placeholder"
PORT_TEMPLATES="
  # apps/web/.env.local:NEXT_PUBLIC_API_URL=http://localhost:{PORT_api}
  # .env:DATABASE_URL=postgresql://user:pass@localhost:{PORT_postgres}/db
"

# MCP servers — written to ~/.claude.json with resolved ports
# Format: "name:command:args"
MCP_SERVERS="
  # my-server:npx:tsx mcp/host/src/index.ts
"

# MCP environment variables (supports {PORT_servicename} placeholders)
# Format: "server_name:KEY=value"
MCP_ENV="
  # my-server:API_URL=http://localhost:{PORT_api}
  # my-server:ENVIRONMENT=local
"

# Database migration tool
MIGRATE_TOOL="$MIGRATE_TOOL"

# Database credentials (extract from docker-compose.yaml)
DB_USER="postgres"
DB_PASS="postgres"
DB_NAME="postgres"

# Setup steps (executed in order by 'hatch setup')
# Space-separated list
SETUP_STEPS="docker:up deps:install migrate:execute"

# Custom hooks file (optional)
HOOKS_FILE="hatch.hooks.sh"

# Advanced: Base port for main workspace (default: 1481)
# DEFAULT_BASE_PORT=1481
EOFCONFIG

_success "Created $CONFIG_FILE"
echo ""
echo "Next steps:"
echo "  1. Edit $CONFIG_FILE to configure services"
echo "  2. Add DOCKER_SERVICES, DOCKER_EXTRAS, and DEV_SERVERS"
echo "  3. Run: hatch setup"
